DROP TABLE suivi_abonnement_omnis_db.notifications;
DROP TABLE suivi_abonnement_omnis_db.abonnements;
DROP TABLE suivi_abonnement_omnis_db.departement_user;
DROP TABLE suivi_abonnement_omnis_db.users;
DROP TABLE suivi_abonnement_omnis_db.fournisseurs;
DROP TABLE suivi_abonnement_omnis_db.categories;
DROP TABLE suivi_abonnement_omnis_db.departements;
DROP TABLE suivi_abonnement_omnis_db.conversations;
DROP TABLE suivi_abonnement_omnis_db.messages;

TRUNCATE TABLE suivi_abonnement_omnis_db.notifications;
TRUNCATE TABLE suivi_abonnement_omnis_db.abonnements;
TRUNCATE TABLE suivi_abonnement_omnis_db.departement_user;
TRUNCATE TABLE suivi_abonnement_omnis_db.users;
TRUNCATE TABLE suivi_abonnement_omnis_db.fournisseurs;
TRUNCATE TABLE suivi_abonnement_omnis_db.categories;
TRUNCATE TABLE suivi_abonnement_omnis_db.departements;
TRUNCATE TABLE suivi_abonnement_omnis_db.conversations;
TRUNCATE TABLE suivi_abonnement_omnis_db.messages;



